### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by jmukhtar** [mmalecki/terraform-state-merge#1]
Hi

I am trying to run this code but it's failing with the above error.

`root@c3a88e427618:/var/tmp/terraform# terraform-state-merge terraform.tfstate generated/aws/sg/eu-west-1/terraform.tfstate
/usr/local/lib/node_modules/terraform-state-merge/bin/terraform-state-merge:16
  modules.forEach((m) => {
          ^

TypeError: Cannot read property 'forEach' of undefined
    at stash (/usr/local/lib/node_modules/terraform-state-merge/bin/terraform-state-merge:16:11)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/terraform-state-merge/bin/terraform-state-merge:22:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)`

Any idea how can i fix it?

**Comment by jmukhtar** [comment]
user error... 2 files had different structures
