### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by ChapChap** [mmalecki/terraform-state-merge#2]
10:22 ❯ terraform-state-merge aws-environments.json aws-environments-network.json
/Users/me/.nvm/versions/node/v12.18.4/lib/node_modules/terraform-state-merge/bin/terraform-state-merge:16
  modules.forEach((m) => {
          ^

TypeError: Cannot read property 'forEach' of undefined
    at stash (/Users/me/.nvm/versions/node/v12.18.4/lib/node_modules/terraform-state-merge/bin/terraform-state-merge:16:11)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v12.18.4/lib/node_modules/terraform-state-merge/bin/terraform-state-merge:22:9)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by ChapChap** [comment]
This relates to https://github.com/mmalecki/terraform-state-merge/issues/1 but I think that this error can be caught in a nicer way.

**Comment by oliverisaac** [comment]
This is an issue because the tfstate no longer has a `modules` key, just a `resources` key. This is fixed here: https://github.com/oliverisaac/terraform-state-merge/blob/master/bin/terraform-state-merge

**Comment by ChapChap** [comment]
@mmalecki Is it possible to merge @oliverisaac's fix ?

**Comment by mmalecki** [comment]
For sure! Please PR, I'll gladly review, merge and (with @oliverisaac's consent) share ownership.
